<?php

function uzc_gazes_theme()
{
    return [
        'soil-sample-measurements' => [
            'variables' => [],
            'template' => 'soil-sample-measurements',
        ],
        'gas-measurements' => [
          'variables' => [],
          'template' => 'gas-measurements',
        ],
        'gas-measurements-lbtu' => [
          'variables' => [],
          'template' => 'gas-measurements-lbtu',
        ],
        'meteo-data' => [
          'variables' => [],
          'template' => 'meteo-data',
        ],
        'combined-measurements' => [
          'variables' => [],
          'template' => 'combined-measurements',
        ],
        'stende-parameters-all' => [
            'variables' => [],
            'template' => 'stende-parameters-all',
        ],
        'agriculture_machinery_cost' => [
            'template' => 'agriculture_machinery_cost',
        ],
    ];
}
