TRUNCATE uzc_gazes.codifier;
CALL uzc_gazes.create_codifier('categories', 'Kategorijas');
CALL uzc_gazes.create_codifier('tractors', 'Traktori', 'categories');
CALL uzc_gazes.create_codifier('tractors', 'Traktori');
CALL uzc_gazes.create_codifier('agriculture_tractor', 'Tractors', 'tractors');
CALL uzc_gazes.create_codifier('agricultural_harvesters', 'Kombaini', 'categories');
CALL uzc_gazes.create_codifier('agricultural_harvesters', 'Kombaini');
CALL uzc_gazes.create_codifier('potato_harvester', 'Kartupeļu novākšanas kombains', 'agricultural_harvesters');
CALL uzc_gazes.create_codifier('combine_harvester', 'Graudaugu kombains', 'agricultural_harvesters');
CALL uzc_gazes.create_codifier('sowing_and_planting_machines', 'Sējas un stādāmā tehnika', 'categories');
CALL uzc_gazes.create_codifier('sowing_and_planting_machines', 'Sējas un stādāmā tehnika');
CALL uzc_gazes.create_codifier('drills', 'Sējmašīna', 'sowing_and_planting_machines');
CALL uzc_gazes.create_codifier('tillage_machines', 'Augsnes apstrādes tehnika un iekārtas', 'categories');
CALL uzc_gazes.create_codifier('tillage_machines', 'Augsnes apstrādes tehnika un iekārtas');
CALL uzc_gazes.create_codifier('mills', 'Frēze', 'tillage_machines');
CALL uzc_gazes.create_codifier('plough', 'Arkls', 'tillage_machines');
CALL uzc_gazes.create_codifier('hay_and_forage_machines', 'Lopbarības sagatavošanas tehnika', 'categories');
CALL uzc_gazes.create_codifier('hay_and_forage_machines', 'Lopbarības sagatavošanas tehnika');
CALL uzc_gazes.create_codifier('mowers', 'Pļaujmašīna', 'hay_and_forage_machines');
CALL uzc_gazes.create_codifier('fertilization_and_plant_protection_machines', 'Mēslošanas un augu aizsardzības tehnika', 'categories');
CALL uzc_gazes.create_codifier('fertilization_and_plant_protection_machines', 'Mēslošanas un augu aizsardzības tehnika');
CALL uzc_gazes.create_codifier('sprayer', 'Smidzinātājs', 'fertilization_and_plant_protection_machines');
CALL uzc_gazes.create_codifier('cargo_transportation_machines', 'Kravu transportēšanas tehnika', 'categories');
CALL uzc_gazes.create_codifier('cargo_transportation_machines', 'Kravu transportēšanas tehnika');
CALL uzc_gazes.create_codifier('trailer', 'Piekabe', 'cargo_transportation_machines');
CALL uzc_gazes.create_codifier('sowing_and_plant_care_machines', 'Sējumu un stādījumu kopšanas tehnika', 'categories');
CALL uzc_gazes.create_codifier('sowing_and_plant_care_machines', 'Sējumu un stādījumu kopšanas tehnika');
CALL uzc_gazes.create_codifier('forage_harvester', 'Mulčeris', 'sowing_and_plant_care_machines');
CALL uzc_gazes.create_codifier('grass_mower', 'Mauriņa pļaujmašīna', 'sowing_and_plant_care_machines');
CALL uzc_gazes.create_codifier('equipment_level', 'Aprīkojuma līmenis');
CALL uzc_gazes.create_codifier('base', 'Bāzes', 'equipment_level');
CALL uzc_gazes.create_codifier('medium', 'Vidējais', 'equipment_level');
CALL uzc_gazes.create_codifier('premium', 'Premium', 'equipment_level');
CALL uzc_gazes.create_codifier('value_types', 'Vērtību tipi');
CALL uzc_gazes.create_codifier('power', 'Jauda (kW)', 'value_types');
CALL uzc_gazes.create_codifier('weight', 'Masa (kg)', 'value_types');
